### PR TITLE
feat: implement app querier

### PR DESCRIPTION
**Pull request by SweeXordious**
## Overview

Contributes to: https://github.com/celestiaorg/orchestrator-relayer/issues/108
Closes: https://github.com/celestiaorg/orchestrator-relayer/issues/44
## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Comment by SweeXordious** [comment]
Still trying to fix the race happening

**Review by evan-forbes — APPROVED** [review]
that race is weird... is it flakey, or fixed here?

**Comment by SweeXordious** [comment]
@evan-forbes It's not fixed,  it's just skipped when running tests with `-short` flag. The thing is, many races are coming from the cosmos-sdk (baseapp, IAVL...). So, I don't think they should be fixed here (or fixed at all, because they're only used for tests)

**Comment by evan-forbes** [comment]
do you know why we see those races here but not in app?

**Comment by SweeXordious** [comment]
It's mainly coming from the cosmos-sdk. But, the reason, I guess, we're not seeing those in the app is because:
- We only have 1 testing suite that uses the test node inside the app
- The tests are skipped when running with `-race` because of the short flag: https://github.com/celestiaorg/celestia-app/blob/332a17fb9068ffec797a1f1715d628ab60f4fcae/Makefile#L113.

**Comment by evan-forbes** [comment]
ahh I see! hmm. from what I could tell when running our two testnode tests with the race detector manually turned on, it looks like this might actually have to do with the extra PFB checks and the cosmos-sdk reading the header from the CheckTxState during ProcessProposal. I'm still confused as to why its an issue, because the only time we write to that checktx state is after we commit the block.

**Comment by SweeXordious** [comment]
Update: Just tested on the Celestia-app repo with running:
```
$  go test -mod=readonly -race  ./... 
```
And I have the race in the baseapp.

Also, there is a race on the `fuzz_abci_test`

**Comment by SweeXordious** [comment]
Should I create an issue in Celestia-app to fix these races?

Also, can I merge this PR?

**Comment by evan-forbes** [comment]
> Should I create an issue in Celestia-app to fix these races?

yeah definitely! thx

> Also, can I merge this PR?

yeah the issues are outside of the scope of this repo, thanks for investigating!

**Comment by SweeXordious** [comment]
https://github.com/celestiaorg/celestia-app/issues/1369

Sure, it's a pleasure. Thanks a lot  for your help :D

**Pull request merged**
