### PR TITLE
feat: implement valset confirm signature validation

### PR DESCRIPTION
**Pull request by SweeXordious**
## Overview

Closes https://github.com/celestiaorg/orchestrator-relayer/issues/224

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Review by evan-forbes — COMMENTED** [review]
are the sign bytes deterministic? like, could we generate them or do we have to keep them in the confirm?

**Comment by SweeXordious** [comment]
To generate them, we need to have access to the valset: validators + threshold, which we don't  have access to in here.

This will change in an upcoming PR because of this https://github.com/celestiaorg/orchestrator-relayer/issues/225

This PR prepares for the next one that would make the `signBytes` and the `commitment` as part of the key

**Comment by evan-forbes** [comment]
> This PR prepares for the next one that would make the signBytes and the commitment as part of the key

ok I think I see

> To generate them, we need to have access to the valset: validators + threshold, which we don't have access to in here.

it is deterministic though, and all we have to do is query for that, correct?

**Review by evan-forbes — APPROVED** [review]

**Comment by SweeXordious** [comment]
> it is deterministic though, and all we have to do is query for that, correct?

Yes, https://github.com/celestiaorg/celestia-app/blob/953860c4b8c3730377ba860ce7a6360bd855ddda/x/qgb/types/valset.go#L31-L55

**Pull request merged**
